environment:
  # ...
  
# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  # - git config --global core.autocrlf input

platform: 
- x64
# - Win32

configuration: 
# - Debug
# - Release

install:
  # by default, all script lines are interpreted as batch
  - git submodule update --init --recursive

before_build:
  - echo Running cmake...
  - pwd
  - scripts\cmake-make.bat
  # - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%P%

build:
  project: ALL_BUILD.vcxproj      # path to Visual Studio solution or project

# scripts to run after build
after_build:
  # ...

artifacts:
  # ...

deploy_script:
  # ...
  
